// Generated by CoffeeScript 1.8.0
(function () {
    (function ($, window) {
        var Plugin, defaults, locales, pluginName;
        pluginName = 'timer';
        locales = {
            ru: {
                days: ['день', 'дней', 'дней'],
                hours: ['час', 'часов', 'часов'],
                minuts: ['минута', 'минут', 'минут'],
                seconds: ['секунда', 'секунд', 'секунд']
            }
            
        };
        defaults = {
            lang: 'ru',
            updateTime: 1000,
            onEnd: $.noop
        };
        Plugin = (function () {
            function Plugin(el, options) {
                this.el = el;
                this.$el = $(this.el);
                $.extend(this, defaults, this.$el.data(), options);
                if (!this.locale) {
                    this.locale = locales[this.lang];
                }
                this.startDate = new Date();
                this.template = this.$el.html();
                if (Object.prototype.toString.call(this.endDate) !== '[object Date]') {
                    this.endDate = this.parseDate(this.endDate, this.dateFormat);
                }
                this.start();
            }

            Plugin.prototype.parseDate = function (str, format) {
                var data, now;
                str = str.split(/[^\d]/g);
                format = format.split(/[^%yMdhms]/g);
                now = new Date();
                data = {
                    y: now.getFullYear(),
                    M: now.getMonth() + 1,
                    d: now.getDate(),
                    h: 0,
                    m: 0,
                    s: 0
                };
                format.forEach(function (val, index) {
                    var key;
                    key = val.slice(1);
                    return data[key] = str[index];
                });
                return new Date(data.y, data.M - 1, data.d, data.h, data.m, data.s);
            };

            Plugin.prototype.start = function () {
                this.interval = setInterval((function (_this) {
                    return function () {
                        return _this.update();
                    };
                })(this), this.updateTime);
                return this.update();
            };

            Plugin.prototype.end = function () {
                clearInterval(this.interval);
                this.$el.trigger("" + pluginName + ":stop");
                return this.onEnd();
            };

            Plugin.prototype.update = function () {
                var days, devider, hours, minuts, now, range, seconds;
                now = new Date();
                range = this.endDate - now;
                if (range <= 0) {
                    this.end();
                    return;
                }
                devider = 1000 * 60 * 60 * 24;
                days = Math.floor(range / devider);
                range = range - days * devider;
                devider = 1000 * 60 * 60;
                hours = Math.floor(range / devider);
                range = range - hours * devider;
                devider = 1000 * 60;
                minuts = Math.floor(range / devider);
                range = range - minuts * devider;
                devider = 1000;
                seconds = Math.floor(range / devider);
                return this.render({
                    days: days,
                    hours: hours,
                    minuts: minuts,
                    seconds: seconds
                });
            };

            Plugin.prototype.render = function (data) {
                var html;
                html = this.template;
                $.each(this.locale, (function (_this) {
                    return function (key, values) {
                        return html = html.replace(new RegExp('%' + key + '%', 'g'), _this.leadingZero(data[key])).replace(new RegExp('%' + key.toUpperCase() + '%', 'g'), _this.spellCount(data[key], values));
                    };
                })(this));
                return this.$el.html(html);
            };

            Plugin.prototype.spellCount = function (num, variants) {
                if ($.isArray(variants)) {
                    if (num % 10 === 1 && num % 100 !== 11) {
                        return variants[0];
                    } else if (num % 10 >= 2 && num % 10 <= 4 && (num % 100 < 10 || num % 100 >= 20)) {
                        return variants[1];
                    } else {
                        return variants[2];
                    }
                } else {
                    return variants;
                }
            };

            Plugin.prototype.leadingZero = function (num) {
                var result = '';

                if (num < 10) {
                    num = '0' + num;
                }
                num = num + '';

                for (var i = 0; i < num.length; i++) {
                    result += '<span>' + num[i] + '</span>';
                }

                return result;
            };

            return Plugin;

        })();
        return $.fn[pluginName] = function (options) {
            return this.each(function () {
                if (!$.data(this, pluginName)) {
                    return $.data(this, pluginName, new Plugin(this, options));
                }
            });
        };
    })(jQuery, window);

}).call(this);

//# sourceMappingURL=timer.jquery.js.map